[package]
name = "gbc"
version = "0.1.0"
resolver = "2"
authors = ["Caio Tavares <caio.tavares11@gmail.com>"]
edition = "2018"

[dependencies]
winit = "0.25.0"
wgpu = "0.11.0"
sdl2 = "0.35.1"
pixels = "0.7.0"
