#[derive(Debug, PartialEq)]
pub enum ExtendedInstruction {
    // Rotate
    RLC_A,
    RLC_B,
    RLC_C,
    RLC_D,
    RLC_E,
    RLC_H,
    RLC_L,
    RLC_HL,

    RRC_A,
    RRC_B,
    RRC_C,
    RRC_D,
    RRC_E,
    RRC_H,
    RRC_L,
    RRC_HL,

    RL_A,
    RL_B,
    RL_C,
    RL_D,
    RL_E,
    RL_H,
    RL_L,
    RL_HL,

    RR_A,
    RR_B,
    RR_C,
    RR_D,
    RR_E,
    RR_H,
    RR_L,
    RR_HL,

    SLA_A,
    SLA_B,
    SLA_C,
    SLA_D,
    SLA_E,
    SLA_H,
    SLA_L,
    SLA_HL,

    SRA_A,
    SRA_B,
    SRA_C,
    SRA_D,
    SRA_E,
    SRA_H,
    SRA_L,
    SRA_HL,

    SWAP_A,
    SWAP_B,
    SWAP_C,
    SWAP_D,
    SWAP_E,
    SWAP_H,
    SWAP_L,
    SWAP_HL,

    SRL_A,
    SRL_B,
    SRL_C,
    SRL_D,
    SRL_E,
    SRL_H,
    SRL_L,
    SRL_HL,
}

impl ExtendedInstruction {
    pub fn decode(byte: u8) -> ExtendedInstruction {
        match byte {
            0x00 => ExtendedInstruction::RLC_B,
            0x01 => ExtendedInstruction::RLC_C,
            0x02 => ExtendedInstruction::RLC_D,
            0x03 => ExtendedInstruction::RLC_E,
            0x04 => ExtendedInstruction::RLC_H,
            0x05 => ExtendedInstruction::RLC_L,
            0x06 => ExtendedInstruction::RLC_HL,
            0x07 => ExtendedInstruction::RLC_A,
            0x08 => ExtendedInstruction::RRC_B,
            0x09 => ExtendedInstruction::RRC_C,
            0x0A => ExtendedInstruction::RRC_D,
            0x0B => ExtendedInstruction::RRC_E,
            0x0C => ExtendedInstruction::RRC_H,
            0x0D => ExtendedInstruction::RRC_L,
            0x0E => ExtendedInstruction::RRC_HL,
            0x0F => ExtendedInstruction::RRC_A,

            0x10 => ExtendedInstruction::RL_B,
            0x11 => ExtendedInstruction::RL_C,
            0x12 => ExtendedInstruction::RL_D,
            0x13 => ExtendedInstruction::RL_E,
            0x14 => ExtendedInstruction::RL_H,
            0x15 => ExtendedInstruction::RL_L,
            0x16 => ExtendedInstruction::RL_HL,
            0x17 => ExtendedInstruction::RL_A,
            0x18 => ExtendedInstruction::RR_B,
            0x19 => ExtendedInstruction::RR_C,
            0x1A => ExtendedInstruction::RR_D,
            0x1B => ExtendedInstruction::RR_E,
            0x1C => ExtendedInstruction::RR_H,
            0x1D => ExtendedInstruction::RR_L,
            0x1E => ExtendedInstruction::RR_HL,
            0x1F => ExtendedInstruction::RR_A,

            0x20 => ExtendedInstruction::SLA_B,
            0x21 => ExtendedInstruction::SLA_C,
            0x22 => ExtendedInstruction::SLA_D,
            0x23 => ExtendedInstruction::SLA_E,
            0x24 => ExtendedInstruction::SLA_H,
            0x25 => ExtendedInstruction::SLA_L,
            0x26 => ExtendedInstruction::SLA_HL,
            0x27 => ExtendedInstruction::SLA_A,
            0x28 => ExtendedInstruction::SRA_B,
            0x29 => ExtendedInstruction::SRA_C,
            0x2A => ExtendedInstruction::SRA_D,
            0x2B => ExtendedInstruction::SRA_E,
            0x2C => ExtendedInstruction::SRA_H,
            0x2D => ExtendedInstruction::SRA_L,
            0x2E => ExtendedInstruction::SRA_HL,
            0x2F => ExtendedInstruction::SRA_A,

            0x30 => ExtendedInstruction::SWAP_B,
            0x31 => ExtendedInstruction::SWAP_C,
            0x32 => ExtendedInstruction::SWAP_D,
            0x33 => ExtendedInstruction::SWAP_E,
            0x34 => ExtendedInstruction::SWAP_H,
            0x35 => ExtendedInstruction::SWAP_L,
            0x36 => ExtendedInstruction::SWAP_HL,
            0x37 => ExtendedInstruction::SWAP_A,
            0x38 => ExtendedInstruction::SRL_B,
            0x39 => ExtendedInstruction::SRL_C,
            0x3A => ExtendedInstruction::SRL_D,
            0x3B => ExtendedInstruction::SRL_E,
            0x3C => ExtendedInstruction::SRL_H,
            0x3D => ExtendedInstruction::SRL_L,
            0x3E => ExtendedInstruction::SRL_HL,
            0x3F => ExtendedInstruction::SRL_A,

            0x40 => todo!(),
            0x41 => todo!(),
            0x42 => todo!(),
            0x43 => todo!(),
            0x44 => todo!(),
            0x45 => todo!(),
            0x46 => todo!(),
            0x47 => todo!(),
            0x48 => todo!(),
            0x49 => todo!(),
            0x4A => todo!(),
            0x4B => todo!(),
            0x4C => todo!(),
            0x4D => todo!(),
            0x4E => todo!(),
            0x4F => todo!(),

            0x50 => todo!(),
            0x51 => todo!(),
            0x52 => todo!(),
            0x53 => todo!(),
            0x54 => todo!(),
            0x55 => todo!(),
            0x56 => todo!(),
            0x57 => todo!(),
            0x58 => todo!(),
            0x59 => todo!(),
            0x5A => todo!(),
            0x5B => todo!(),
            0x5C => todo!(),
            0x5D => todo!(),
            0x5E => todo!(),
            0x5F => todo!(),

            0x60 => todo!(),
            0x61 => todo!(),
            0x62 => todo!(),
            0x63 => todo!(),
            0x64 => todo!(),
            0x65 => todo!(),
            0x66 => todo!(),
            0x67 => todo!(),
            0x68 => todo!(),
            0x69 => todo!(),
            0x6A => todo!(),
            0x6B => todo!(),
            0x6C => todo!(),
            0x6D => todo!(),
            0x6E => todo!(),
            0x6F => todo!(),

            0x70 => todo!(),
            0x71 => todo!(),
            0x72 => todo!(),
            0x73 => todo!(),
            0x74 => todo!(),
            0x75 => todo!(),
            0x76 => todo!(),
            0x77 => todo!(),
            0x78 => todo!(),
            0x79 => todo!(),
            0x7A => todo!(),
            0x7B => todo!(),
            0x7C => todo!(),
            0x7D => todo!(),
            0x7E => todo!(),
            0x7F => todo!(),

            0x80 => todo!(),
            0x81 => todo!(),
            0x82 => todo!(),
            0x83 => todo!(),
            0x84 => todo!(),
            0x85 => todo!(),
            0x86 => todo!(),
            0x87 => todo!(),
            0x88 => todo!(),
            0x89 => todo!(),
            0x8A => todo!(),
            0x8B => todo!(),
            0x8C => todo!(),
            0x8D => todo!(),
            0x8E => todo!(),
            0x8F => todo!(),

            0x90 => todo!(),
            0x91 => todo!(),
            0x92 => todo!(),
            0x93 => todo!(),
            0x94 => todo!(),
            0x95 => todo!(),
            0x96 => todo!(),
            0x97 => todo!(),
            0x98 => todo!(),
            0x99 => todo!(),
            0x9A => todo!(),
            0x9B => todo!(),
            0x9C => todo!(),
            0x9D => todo!(),
            0x9E => todo!(),
            0x9F => todo!(),

            0xA0 => todo!(),
            0xA1 => todo!(),
            0xA2 => todo!(),
            0xA3 => todo!(),
            0xA4 => todo!(),
            0xA5 => todo!(),
            0xA6 => todo!(),
            0xA7 => todo!(),
            0xA8 => todo!(),
            0xA9 => todo!(),
            0xAA => todo!(),
            0xAB => todo!(),
            0xAC => todo!(),
            0xAD => todo!(),
            0xAE => todo!(),
            0xAF => todo!(),

            0xB0 => todo!(),
            0xB1 => todo!(),
            0xB2 => todo!(),
            0xB3 => todo!(),
            0xB4 => todo!(),
            0xB5 => todo!(),
            0xB6 => todo!(),
            0xB7 => todo!(),
            0xB8 => todo!(),
            0xB9 => todo!(),
            0xBA => todo!(),
            0xBB => todo!(),
            0xBC => todo!(),
            0xBD => todo!(),
            0xBE => todo!(),
            0xBF => todo!(),

            0xC0 => todo!(),
            0xC1 => todo!(),
            0xC2 => todo!(),
            0xC3 => todo!(),
            0xC4 => todo!(),
            0xC5 => todo!(),
            0xC6 => todo!(),
            0xC7 => todo!(),
            0xC8 => todo!(),
            0xC9 => todo!(),
            0xCA => todo!(),
            0xCB => todo!(),
            0xCC => todo!(),
            0xCD => todo!(),
            0xCE => todo!(),
            0xCF => todo!(),

            0xD0 => todo!(),
            0xD1 => todo!(),
            0xD2 => todo!(),
            0xD3 => todo!(),
            0xD4 => todo!(),
            0xD5 => todo!(),
            0xD6 => todo!(),
            0xD7 => todo!(),
            0xD8 => todo!(),
            0xD9 => todo!(),
            0xDA => todo!(),
            0xDB => todo!(),
            0xDC => todo!(),
            0xDD => todo!(),
            0xDE => todo!(),
            0xDF => todo!(),

            0xE0 => todo!(),
            0xE1 => todo!(),
            0xE2 => todo!(),
            0xE3 => todo!(),
            0xE4 => todo!(),
            0xE5 => todo!(),
            0xE6 => todo!(),
            0xE7 => todo!(),
            0xE8 => todo!(),
            0xE9 => todo!(),
            0xEA => todo!(),
            0xEB => todo!(),
            0xEC => todo!(),
            0xED => todo!(),
            0xEE => todo!(),
            0xEF => todo!(),

            0xF0 => todo!(),
            0xF1 => todo!(),
            0xF2 => todo!(),
            0xF3 => todo!(),
            0xF4 => todo!(),
            0xF5 => todo!(),
            0xF6 => todo!(),
            0xF7 => todo!(),
            0xF8 => todo!(),
            0xF9 => todo!(),
            0xFA => todo!(),
            0xFB => todo!(),
            0xFC => todo!(),
            0xFD => todo!(),
            0xFE => todo!(),
            0xFF => todo!(),
        }
    }
}
